export const registrarsData = [
  {
    id: 1,
    name: "JUST / EXPERTFOX",
    slug: "just-expertfox",
    logo: "JEF",
    description: "Bureau d'enregistrement accrédité NIC.CI, spécialisé dans les services numériques et l'enregistrement de noms de domaine .CI.",
    phone: "0151092627",
    email: "patricia@just.ci",
    website: "https://www.just.ci",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2015-01-01",
    extensions: [".ci", ".co.ci", ".org.ci"],
    featured: false,
  },
  {
    id: 2,
    name: "AFRIREGISTER",
    slug: "afriregister",
    logo: "AFR",
    description: "Bureau d'enregistrement panafricain accrédité par le NIC.CI pour la gestion des noms de domaine .CI.",
    phone: "+257 78605472",
    email: "suavis@afriregister.com",
    website: "https://www.afriregister.com",
    type: "international",
    status: "accredited",
    country: "International",
    accreditedSince: "2016-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 3,
    name: "AKASSOH",
    slug: "akassoh",
    logo: "AKS",
    description: "Registrar ivoirien accrédité NIC.CI, offrant des services d'enregistrement et de gestion de noms de domaine .CI.",
    phone: "+225 0544444451 / 0708655362",
    email: "wilfriedn@akassoh.net",
    website: "https://www.akassoh.net",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2017-01-01",
    extensions: [".ci", ".co.ci", ".org.ci"],
    featured: false,
  },
  {
    id: 4,
    name: "AMIRA GLOBAL TECHNOLOGIE",
    slug: "amira-global-technologie",
    logo: "AMG",
    description: "Entreprise technologique ivoirienne proposant des services d'enregistrement de noms de domaine .CI et des solutions numériques.",
    phone: "+225 0505577332 / 0101285084",
    email: "saka@amiraglobaltech.com",
    website: "https://www.amiraglobaltech.com",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2018-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 5,
    name: "ASCIO TECHNOLOGIE",
    slug: "ascio-technologie",
    logo: "ASC",
    description: "Bureau d'enregistrement international accrédité NIC.CI, opérant depuis l'Europe avec des services de gestion de domaines.",
    phone: "+45 33886100 / +49.2283296859",
    email: "callback@speednic.net",
    website: "https://www.speednic.net",
    type: "international",
    status: "accredited",
    country: "International",
    accreditedSince: "2014-01-01",
    extensions: [".ci", ".co.ci", ".org.ci", ".net.ci"],
    featured: false,
  },
  {
    id: 6,
    name: "ASSISTWEB / CACE",
    slug: "assistweb-cace",
    logo: "AWC",
    description: "Registrar ivoirien proposant des services d'assistance web et d'enregistrement de noms de domaine .CI aux entreprises locales.",
    phone: "+225 2722591305 / 0102032819",
    email: "support.assistweb@gmail.com",
    website: "https://www.assistweb.ci",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2016-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 7,
    name: "AWEBSI / AFRICANTRADE",
    slug: "awebsi-africantrade",
    logo: "AWB",
    description: "Bureau d'enregistrement ivoirien accrédité NIC.CI, spécialisé dans les solutions web et le commerce digital en Afrique.",
    phone: "+225 0709474800",
    email: "pekangocoulibaly@gmail.com",
    website: "https://www.awebsi.ci",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2017-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 8,
    name: "ICTINA / PIECE OF LOVE",
    slug: "ictina-piece-of-love",
    logo: "ICT",
    description: "Registrar ivoirien accrédité NIC.CI, offrant des services d'enregistrement de domaines .CI et des solutions TIC.",
    phone: "+225 0707579216",
    email: "visible@pieceoflove.africa",
    website: "https://www.pieceoflove.africa",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2019-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 9,
    name: "VENAME / CINETCOME",
    slug: "vename-cinetcome",
    logo: "VEN",
    description: "Bureau d'enregistrement ivoirien accrédité NIC.CI, proposant des services de noms de domaine .CI et de connectivité.",
    phone: "+225 0709145146",
    email: "soungalo.dosso@vename.com",
    website: "https://www.vename.com",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2018-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 10,
    name: "CSC CORPORATE",
    slug: "csc-corporate",
    logo: "CSC",
    description: "Leader mondial dans la gestion de noms de domaine et la protection de marques, accrédité NIC.CI pour les domaines .CI.",
    phone: "+1 3026365400",
    email: "cctld-billing@cscinfo.com",
    website: "https://www.cscglobal.com",
    type: "international",
    status: "accredited",
    country: "International",
    accreditedSince: "2013-01-01",
    extensions: [".ci", ".co.ci", ".org.ci", ".net.ci"],
    featured: true,
  },
  {
    id: 11,
    name: "DATACONNECT / EPISTROPHE",
    slug: "dataconnect-epistrophe",
    logo: "DAT",
    description: "Registrar ivoirien accrédité NIC.CI, proposant des services d'hébergement, de connectivité et d'enregistrement de domaines .CI.",
    phone: "+225 0544027070 / 2722548500",
    email: "domaines@dataconnect.africa",
    website: "https://www.dataconnect.africa",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2015-01-01",
    extensions: [".ci", ".co.ci", ".org.ci", ".net.ci"],
    featured: true,
  },
  {
    id: 12,
    name: "GRANSY",
    slug: "gransy",
    logo: "GRN",
    description: "Bureau d'enregistrement européen accrédité NIC.CI, spécialisé dans la gestion de noms de domaine internationaux et africains.",
    phone: "+420 732954549",
    email: "info@regtons.com",
    website: "https://www.regtons.com",
    type: "international",
    status: "accredited",
    country: "International",
    accreditedSince: "2016-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 13,
    name: "KHEUWEUL",
    slug: "kheuweul",
    logo: "KHW",
    description: "Bureau d'enregistrement ouest-africain accrédité NIC.CI, proposant des services de noms de domaine .CI depuis le Sénégal.",
    phone: "+221.338212939",
    email: "mouhamet.diop@kheweul.com",
    website: "https://www.kheweul.com",
    type: "international",
    status: "accredited",
    country: "International",
    accreditedSince: "2017-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 14,
    name: "LEXSYNERGY",
    slug: "lexsynergy",
    logo: "LEX",
    description: "Spécialiste international de la gestion de domaines et de la protection de marques, accrédité NIC.CI pour les domaines .CI.",
    phone: "+44 2031370459",
    email: "support@lexsynergy.com",
    website: "https://www.lexsynergy.com",
    type: "international",
    status: "accredited",
    country: "International",
    accreditedSince: "2015-01-01",
    extensions: [".ci", ".co.ci", ".org.ci"],
    featured: false,
  },
  {
    id: 15,
    name: "MTN CI",
    slug: "mtn-ci",
    logo: "MTN",
    description: "Opérateur télécom leader en Côte d'Ivoire, proposant des services d'enregistrement de noms de domaine .CI pour les particuliers et entreprises.",
    phone: "+225 0504188908",
    email: "samuel.lorougnon@mtn.com",
    website: "https://www.mtn.ci",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2010-01-01",
    extensions: [".ci", ".co.ci", ".org.ci", ".net.ci"],
    featured: true,
  },
  {
    id: 16,
    name: "NETIM",
    slug: "netim",
    logo: "NTM",
    description: "Bureau d'enregistrement français accrédité NIC.CI, offrant des services complets de gestion de noms de domaine .CI.",
    phone: "+33 972307473",
    email: "adrien@netim.com",
    website: "https://www.netim.com",
    type: "international",
    status: "accredited",
    country: "International",
    accreditedSince: "2014-01-01",
    extensions: [".ci", ".co.ci", ".org.ci"],
    featured: false,
  },
  {
    id: 17,
    name: "PLANETHOSTER NIC",
    slug: "planethoster-nic",
    logo: "PLH",
    description: "Hébergeur web international accrédité NIC.CI, proposant des services d'enregistrement de domaines .CI et d'hébergement cloud.",
    phone: "+1.514.360.8573",
    email: "quentin.clarenne@planethoster.info",
    website: "https://www.planethoster.com",
    type: "international",
    status: "accredited",
    country: "International",
    accreditedSince: "2016-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 18,
    name: "POWERLINE C.",
    slug: "powerline-c",
    logo: "PWL",
    description: "Bureau d'enregistrement ivoirien accrédité NIC.CI, spécialisé dans les solutions numériques et la gestion de domaines .CI.",
    phone: "+225 0708721372",
    email: "serge.mian@b-technologies.ci",
    website: "https://www.b-technologies.ci",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2017-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 19,
    name: "SIGMAS PERFORMANCE",
    slug: "sigmas-performance",
    logo: "SIG",
    description: "Registrar ivoirien accrédité NIC.CI, proposant des services TIC et d'enregistrement de noms de domaine .CI aux entreprises.",
    phone: "+225 2122 00 20 77 / 05 05 50 05 57",
    email: "support@ticafrique.com",
    website: "https://www.ticafrique.com",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2015-01-01",
    extensions: [".ci", ".co.ci", ".org.ci"],
    featured: false,
  },
  {
    id: 20,
    name: "CLOUD4AFRICA / VEONE",
    slug: "cloud4africa-veone",
    logo: "C4A",
    description: "Acteur du cloud computing en Afrique, accrédité NIC.CI, proposant des services d'hébergement et d'enregistrement de domaines .CI.",
    phone: "+225 25 20 00 46 40 / 0554026161",
    email: "renaud.koutouan@cloud4africa.net",
    website: "https://www.cloud4africa.net",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2018-01-01",
    extensions: [".ci", ".co.ci", ".org.ci", ".net.ci"],
    featured: true,
  },
  {
    id: 21,
    name: "VIPNET",
    slug: "vipnet",
    logo: "VIP",
    description: "Fournisseur d'accès Internet ivoirien accrédité NIC.CI, proposant des services d'hébergement et d'enregistrement de noms de domaine.",
    phone: "+225 21 22 52 62 00 / 0777 74 84 50",
    email: "eric.assi@vipnet.ci",
    website: "https://www.vipnet.ci",
    type: "isp",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2012-01-01",
    extensions: [".ci", ".co.ci", ".net.ci"],
    featured: true,
  },
  {
    id: 22,
    name: "WEBLOGY",
    slug: "weblogy",
    logo: "WBL",
    description: "Agence web et bureau d'enregistrement ivoirien accrédité NIC.CI, dédié à la création web et la gestion de domaines .CI.",
    phone: "+225 0504952220 / 0506351711",
    email: "nouattara@weblogie.ci",
    website: "https://www.weblogie.ci",
    type: "hosting",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2019-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 23,
    name: "XSELSERVICES",
    slug: "xselservices",
    logo: "XSL",
    description: "Bureau d'enregistrement ivoirien accrédité NIC.CI, proposant des services numériques et d'enregistrement de domaines .CI.",
    phone: "+225 0101000364",
    email: "direction@xsel-services.com",
    website: "https://www.xsel-services.com",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2018-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 24,
    name: "SAFEBRANDS",
    slug: "safebrands",
    logo: "SFB",
    description: "Expert international en protection de marques et gestion de noms de domaine, accrédité NIC.CI pour les domaines .CI.",
    phone: "+33.488662222",
    email: "clientele@safebrands.com",
    website: "https://www.safebrands.com",
    type: "international",
    status: "accredited",
    country: "International",
    accreditedSince: "2014-01-01",
    extensions: [".ci", ".co.ci", ".org.ci"],
    featured: false,
  },
  {
    id: 25,
    name: "ORANGE CI / AVISO",
    slug: "orange-ci-aviso",
    logo: "OCI",
    description: "Opérateur télécom et hébergeur web leader en Côte d'Ivoire, accrédité NIC.CI pour l'enregistrement de domaines .CI.",
    phone: "+225 2720348460 / 0708904662",
    email: "rokiatou.kouyate@orange.com",
    website: "https://www.orange.ci",
    type: "isp",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2009-01-01",
    extensions: [".ci", ".co.ci", ".org.ci", ".net.ci"],
    featured: true,
  },
  {
    id: 26,
    name: "I2S2",
    slug: "i2s2",
    logo: "I2S",
    description: "Bureau d'enregistrement ivoirien accrédité NIC.CI, proposant des solutions informatiques et d'enregistrement de noms de domaine .CI.",
    phone: "+225 0505302159",
    email: "mori@i2s2.com",
    website: "https://www.i2s2.com",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2017-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 27,
    name: "SAFENAMES",
    slug: "safenames",
    logo: "SFN",
    description: "Bureau d'enregistrement international accrédité NIC.CI, spécialisé dans la protection de marques et la gestion de domaines .CI.",
    phone: "+44 1908200022",
    email: "thierry.kouebitra@safenames.net",
    website: "https://www.safenames.net",
    type: "international",
    status: "accredited",
    country: "International",
    accreditedSince: "2013-01-01",
    extensions: [".ci", ".co.ci", ".org.ci"],
    featured: false,
  },
  {
    id: 28,
    name: "WASSI TECHNOLOGIE",
    slug: "wassi-technologie",
    logo: "WST",
    description: "Entreprise technologique ivoirienne accrédite NIC.CI, offrant des services d'enregistrement de domaines .CI et de solutions numériques.",
    phone: "+225 2122522522 / 0140200045",
    email: "info@wassi.ci",
    website: "https://www.wassi.ci",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2016-01-01",
    extensions: [".ci", ".co.ci", ".org.ci"],
    featured: false,
  },
  {
    id: 29,
    name: "SNDI",
    slug: "sndi",
    logo: "SND",
    description: "Société nationale de développement informatique, registrar ivoirien accrédité NIC.CI pour la gestion de noms de domaine .CI.",
    phone: "+225 0707490849",
    email: "herve.akeboue@sndi.ci",
    website: "https://www.sndi.ci",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2011-01-01",
    extensions: [".ci", ".co.ci", ".org.ci", ".net.ci"],
    featured: false,
  },
  {
    id: 30,
    name: "KIP SERVICES",
    slug: "kip-services",
    logo: "KIP",
    description: "Bureau d'enregistrement ivoirien accrédité NIC.CI, proposant des services d'enregistrement de noms de domaine .CI.",
    phone: "+225 0544044443",
    email: "osorho@ekiptech.com",
    website: "https://www.ekiptech.com",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2019-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 31,
    name: "SIRIUS TECHNO / CONNECTYC",
    slug: "sirius-techno-connectyc",
    logo: "STC",
    description: "Registrar ivoirien accrédité NIC.CI, offrant des services de connectivité et d'enregistrement de noms de domaine .CI.",
    phone: "+225 0707070133",
    email: "moussa.diomande@gmail.com",
    website: "https://www.connectyc.ci",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2018-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 32,
    name: "LABEL",
    slug: "label",
    logo: "LBL",
    description: "Bureau d'enregistrement ivoirien accrédité NIC.CI, proposant des services de gestion de noms de domaine .CI.",
    phone: "+225 21258074 / 0748212897",
    email: "gomez.athe@labelci.com",
    website: "https://www.labelci.com",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2017-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 33,
    name: "DMEDIA",
    slug: "dmedia",
    logo: "DMD",
    description: "Agence de communication et bureau d'enregistrement ivoirien accrédité NIC.CI, spécialisé dans les services numériques.",
    phone: "+225 25 20 22 40 72",
    email: "dossoissouf@gmail.com",
    website: "https://www.dmedia.ci",
    type: "local",
    status: "accredited",
    country: "Côte d'Ivoire",
    accreditedSince: "2018-01-01",
    extensions: [".ci", ".co.ci"],
    featured: false,
  },
  {
    id: 34,
    name: "MARKMONITOR",
    slug: "markmonitor",
    logo: "MMK",
    description: "Leader mondial dans la protection de marques en ligne et la gestion de noms de domaine, accrédité NIC.CI pour les domaines .CI.",
    phone: "+1.2083895740",
    email: "ccops@markmonitor.com",
    website: "https://www.markmonitor.com",
    type: "international",
    status: "accredited",
    country: "International",
    accreditedSince: "2012-01-01",
    extensions: [".ci", ".co.ci", ".org.ci", ".net.ci"],
    featured: true,
  },
];